In [3]:
import numpy as np

# Crea un arreglo unidimensional con elementos comprendidos entre 1 y 9
arr = np.arange(1, 10)
print(arr)


[1 2 3 4 5 6 7 8 9]


list1=arr.tolist()
print(list1)

#CREACION DE COPIAS Y VISTAS DE ARREGLOS EN NUMPY

In [4]:
#Crea un arreglo  de 2x2 con numeros comprendidos entre 1 y 4
arr=np.arange(1,5).reshape(2,2)
print(arr)

[[1 2]
 [3 4]]


In [5]:
# Aigna el contenido de un arreglo a otro, sin copiarlo
arr_no_copia=arr
print(arr_no_copia)

[[1 2]
 [3 4]]


In [6]:
#Copia el contenido de un arreglo en otro
arr_copia=arr.copy()
print(arr_copia)

[[1 2]
 [3 4]]


In [7]:
#Crea un arreglo usando una vista
arr_vista=arr.view()
print(arr_vista)


[[1 2]
 [3 4]]


In [8]:
#Despliega nobres de los arrgrelos creados
print("Arreglo Original: ",id(arr))
print("Arreglo asignado",id(arr_no_copia))
print("Arreglo Copuado",id(arr_copia))
print("Vista de arreglo: ",id(arr_vista))

Arreglo Original:  2421063204176
Arreglo asignado 2421063204176
Arreglo Copuado 2421063200720
Vista de arreglo:  2421063204272


In [9]:
#Actualizacion de valores de arreglo original
#Actualiza fila 2 del arreglo
arr[1]=[99,89]
print(arr)

[[ 1  2]
 [99 89]]


In [10]:
#Verifica valores de la vista del arreglo
print("Vista del arreglo:\n",arr_vista)


Vista del arreglo:
 [[ 1  2]
 [99 89]]


In [11]:
#Verifica valores de la copia del arreglo
print("Copia del arreglo: \n",arr_copia)


Copia del arreglo: 
 [[1 2]
 [3 4]]


Seleccion de elementos de un arreglo

In [13]:
#Crea un arreglo unidimensional con elementos comprendidos entre 0 y 9
arr=np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
#Selecciona elementos desde la posicion 4 hasta la posicion 6

print(arr[3:6])

[3 4 5]


In [15]:
#Selecciona los elementos desde la posicion 4 hasta adelante 
print(arr[4:])

[4 5 6 7 8 9]


In [5]:
#Genere un arreglo de 4x4 con numeros comprendidos entre 1 y 16 , particione horizontalmente y verticalmente el arreglo en 4 subarreglos por ultimo crear una vista del arreglo original
import numpy as np

# Genera un arreglo de 4x4 con números entre 1 y 16
arr = np.arange(1, 17).reshape(4, 4)
print("Arreglo original:")
print(arr)

# Particiona el arreglo horizontalmente en 4 subarreglos
horizontal_split = np.hsplit(arr, 4)
print("\nPartición horizontal:")
for subarr in horizontal_split:
    print(subarr)

# Particiona el arreglo verticalmente en 4 subarreglos
vertical_split = np.vsplit(arr, 4)
print("\nPartición vertical:")
for subarr in vertical_split:
    print(subarr)

# Crear una vista del arreglo original
arr_view = arr.view()
print("\nVista del arreglo original:")
print(arr_view)


Arreglo original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Partición horizontal:
[[ 1]
 [ 5]
 [ 9]
 [13]]
[[ 2]
 [ 6]
 [10]
 [14]]
[[ 3]
 [ 7]
 [11]
 [15]]
[[ 4]
 [ 8]
 [12]
 [16]]

Partición vertical:
[[1 2 3 4]]
[[5 6 7 8]]
[[ 9 10 11 12]]
[[13 14 15 16]]

Vista del arreglo original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
